name: Typecheck on push to master

on:
  push:
    branches:
      - master

jobs:
  typecheck:
    name: Run typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run typecheck
        run: bun run typecheck
